const path=require('path');const root=path.resolve(__dirname,'..');
const {chromium}=require('playwright'),minimal=require('@sparticuz/chromium').default,http=require('http'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const server=http.createServer((q,r)=>{const p=q.url.split('?')[0];r.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':'text/html');if(p==='/')return r.end('<div id="top-settings-holder"></div><div id="extensions_settings2"></div><div id="chat"></div>');try{r.end(fs.readFileSync(root+p))}catch{r.writeHead(404).end()}});await new Promise(r=>server.listen(18767,'127.0.0.1',r));const browser=await chromium.launch({executablePath:await minimal.executablePath(),headless:true,args:minimal.args});const page=await browser.newPage({viewport:{width:390,height:844}});let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>route.request().url().startsWith('http://127.0.0.1:18767')?route.continue():route.abort());await page.goto('http://127.0.0.1:18767');await page.evaluate(()=>{
 window.testEvents={};window.toastr={warning:()=>{},error:()=>{}};
 const c={chat:[],characters:[],extensionSettings:{},getRequestHeaders:()=>({'Content-Type':'application/json'}),eventTypes:{APP_READY:'ready'},eventSource:{once:(n,f)=>testEvents[n]=f,on:()=>{},removeListener:()=>{}},getPresetManager:()=>({getPresetList:()=>({preset_names:{},presets:[]}),getSelectedPresetName:()=>''}),saveSettingsDebounced:()=>{}};window.SillyTavern={getContext:()=>c};
 localStorage.setItem('cyll-pear-hub-v1',JSON.stringify({lastTab:'beauty',fontScale:112,zoomFixV36:true,themesMigrated:true}));localStorage.setItem('sb-branches-v1',JSON.stringify({retained:'branch-test'}));
 });await page.evaluate(async()=>{window.testModule=await import('/index.js');testEvents.ready()});assert.equal(await page.locator('#cw-top').count(),0);
 await page.evaluate(()=>{window.TavernHelper={getWorldbookNames:()=>[],getWorldbook:async()=>[],updateWorldbookWith:async()=>[],getGlobalWorldbookNames:()=>[],rebindGlobalWorldbooks:async()=>{},getCharWorldbookNames:()=>({primary:null,additional:[]})}});await page.locator('#cw-top').waitFor();await page.locator('#cw-top').click();await page.locator('#cw-hub').waitFor();assert.equal(await page.locator('[role=tab]').count(),8);
 await page.locator('[role=tab][data-tab="worldbook"]').click();await page.locator('#wb-panel').waitFor();assert.equal(await page.locator('.cw-hub-error').count(),0);await page.locator('[role=tab][data-tab="beauty"]').click();
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cyll-pear-hub-v1')).fontScale),112);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('sb-branches-v1')).retained),'branch-test');await page.evaluate(()=>testModule.onDisable());assert.equal(await page.locator('#cw-top,#cw-fab,#cw-hub,#lili-workbench-extension-settings').count(),0);await page.evaluate(()=>testModule.onEnable());await page.locator('#cw-top').waitFor();assert.equal(await page.locator('#cw-top').count(),1);await page.locator('#lili-workbench-extension-settings button').click();await page.locator('#cw-hub').waitFor();assert.deepEqual(errors,[]);await page.evaluate(()=>testModule.onDisable());await browser.close();server.close();console.log('PASS helper late loading, 8 tabs, worldbook page, original settings/branches retained, disable/re-enable, settings entry; no runtime errors');})().catch(e=>{console.error(e);process.exit(1)});
